### ISSUE TITLE
"Unable to satisfy all constraints on the partition"/"Not all space ... appears to be used"

### ISSUE THREAD

**Issue by Eglisius** [Lanchon/REPIT#18]
Hi Lanchon,

Not sure whether the following warning and error are related. If not, I don't know what to do, else I don't know _how_ to do it. :-) I wouldn't care for eight wasted megabytes (2048 blocks), but I don't know how to convince REPIT2 to continue.

> info: moving/resizing the vfat partition
> Warning: Not all of the space available to /dev/block/mmcblk0 appears to be used, you can fix the GPT to use all of the space (an extra 2048 blocks) or continue with the current setting?
> Error: Unable to satisfy all constraints on the partition.

Logfile attached. Btw, obviously partition no. 11 'sdcard' (UMS) contains more data than its size after repartitioning will be. How would REPIT deal with that?

Many many thanks for your great work!

[recovery_log.zip](https://github.com/Lanchon/REPIT/files/183848/recovery_log.zip)

**Comment by Lanchon** [comment]
hi,

never mind the warning, that has to do with the way Samsung created the PARTITION TABLE on this device, not any particular partition. don't try to manually fix it; just ignore the warning. REPIT ignores it too.

you are trying to resize the internal sdcard:

```
info: current size: partition #11 'sdcard' (UMS): 11784 MiB
info: new size: partition #11 'sdcard' (UMS): 7680 MiB
```

this error:

```
Error: Unable to satisfy all constraints on the partition.
```

means that that can't be done. in all probability, the files currently in the sdcard wouldn't fit in a 7680 MiB partition. free some space in the partition then retry REPIT. if you use the same parameters, then it will continue where it left off. no data will be lost.

REPIT deals by halting in a good situation and letting you choose what to do. it does not roll back work, as that could take a very long time, and you usually want to go forward with your original plan anyway.

the intermediate state will let you use your phone, but some disk space will be unavailable.

if you want to continue, solve the issue and then rerun REPIT. if you want to roll back, run REPIT with the parametes set to your original partition sizes. but please do one of these two options.

**Comment by Eglisius** [comment]
Thanks for your lightning-fast answer.  I deleted some data, and this time it worked perfectly!  (Afterwards, I flashed the latest CM13 nightly, and now I am having trouble with Google Play services.  I will try to flash a newer GApps version.  Still having an old pico version which I used with CM12.)

Btw, I wouldn't have contacted you if REPIT had output a message like, "Maybe some partition contains too much data."

Thanks again for the awesome job you're doing!  Please don't let this anti-social "Chef-Koch" demotivate you ... :-)

**Comment by Lanchon** [comment]
the message 'Unable to satisfy all constraints on the partition' comes upstream from parted. yes, it is very misleading. but i don't want to catch it -since i can't do anything about it- just to explain it better; those things are brittle and tend to break in the future.

but maybe i could add an info message before running parted trying to point the user in the right direction if parted fails.

the horrible message 'Warning: Not all of the space available to...' also comes from parted (even though i'm running it in scripting mode) and there seems to be no way of turning it off.

off topic: you CAN NEVER do a major CM upgrade (say 12.0 to 12.1) without upgrading gapps too. NEVER! i hear that you have to flash CM13 and gapps at the same time sometimes. else force-closes remain even after gapps upgrade. many people end up wiping, hope it's not your case... :(

**Comment by Lanchon** [comment]
created RFE #19
