### ISSUE TITLE
Clarify parted error "Unable to satisfy all constraints on the partition."

### ISSUE THREAD

**Issue by Lanchon** [Lanchon/REPIT#19]
usually means that a vfat partition cannot be resized so small due to its contents.

**Comment by Klesx** [comment]
Hello Lanchon,

Can this work for S4 i9505 with cm13 (but not gapp) installed? Also, my recovery is the one that came with cm13, not sure if thats TWRPx.x.x.

**Comment by Lanchon** [comment]
hi,

you are welcome to create new issues but please don't spam other issues with unrelated questions.

it can support that phone if somebody creates a port for it. you'd probably require TWRP to flash.

please tell me, why do you need to repartition that phone?

porting is simple but if you don't know what TWRP is, it would require too much hand holding and i dont have the time.

if other members want to port, they can start by running the dump tool under TWRP and reporting back the log in a new issue.

**Comment by Klesx** [comment]
I know what TWRP is.
I have clockwork I think but i could check that out, rooted it etc all by
myself so no hand holding.
I want to repartition because I updated CM13 and Gapp pico and it says
insufficient memory just like S2.
Sorry for spamming a diff issue by the way I dont really know the ropes
around Github as yet.

**Comment by Lanchon** [comment]
ok, start by running the dump tool under TWRP and reporting back the log in a new github issue. with that info it might be enough.
