### ISSUE TITLE
Partition reverting to old size - maguro i9250

### ISSUE THREAD

**Issue by suchka** [Lanchon/REPIT#31]
I have successfully installed **lanchon-repit-20160415-system=1.0-cache=0.0605+wipe-data=same-maguro** but i'm having issue with my system partition reverting to old size after installing **cm-12.1-20160417-NIGHTLY-maguro**

Before:
http://i.imgur.com/7DE9fDZ.jpg
After:
http://i.imgur.com/3T5GAsR.jpg

Install log: (second time)
http://i.imgur.com/bH5OhnV.jpg
http://i.imgur.com/v8PjNlq.jpg
http://i.imgur.com/OYgXluT.jpg
http://i.imgur.com/O2wCRY3.jpg
http://i.imgur.com/G4lYNbD.jpg

[recovery.zip](https://github.com/Lanchon/REPIT/files/233090/recovery.zip)

And after i try to install **open_gapps-arm-5.1-mini-20160423** i get this error:
http://i.imgur.com/HMRulN0.jpg
http://i.imgur.com/YtgDLqg.jpg

**Comment by Lanchon** [comment]
hi,

it's not the partition, it's the file system. the partition is the right size. 

since lollipop, most roms (and official stock nexus) distribute the system partition as a file system image rather than a set of files to be extracted. this is a change i'm not particularly fond of, but makes sense to google.

the image is prepared to match and fit exactly in the stock system partition. when this stock-szied image is flashed in your big partition, the result is of course a stock-sized file system that does not cover the full partition area, and a bunch of wasted space after the file system.

to fix this there is a tool by ext4's author, resize2fs, that by default will expand a file system to fill its containing partition. it is included in TWRP's /sbin toolset.

you will need to run this tool after each rom flash. you can run it in several ways:
- manually via adb or TWRP's terminal.
- in TWRP, as follows:
  - click Wipe
  - click Advanced Wipe
  - select System
  - click Repair or Change File System
  - click Resize File System
- using REPIT without arguments:
  - rename it to 'lanchon-repit-2016XXXX-maguro.zip'
  - flash it and REPIT will check and fix all file systems and size them all to fit their partitions if required (with encryption footers if appropriate).
  - EDIT: you can also run REPIT with the same arguments that you originally used to repit your device. the point is, no matter what the configuration, REPIT will always adjust and fix these details, even if conceptually doing a 'no-operation'.

some rom installers automatically run this tool after flashing the system image. you can contact your rom provider and ask them to add this functionality. for instance, official i9100 CM do this.

some rom providers for your device also do this, check this link:
http://forum.xda-developers.com/galaxy-nexus/devs-only/project-galaxy-nexus-partition-2-0-gnp2-t3147253/post66390990

i'm closing this but you can still reply here.
thanks!

**Comment by suchka** [comment]
> click Wipe
> click Advanced Wipe
> select System
>  click Repair or Change File System
>  click Resize File System

This solved problem but now i have another one. I get error on all gapps "unfortunately services has stopped" is there by any chance resizing system caused this problem?

**Comment by Lanchon** [comment]
no. that's a well known issue. i think it happens when you boot android without gapps, then install gapps afterwards and don't wipe data. but you'll have to google it yourself.

**Comment by the-gangster** [comment]
Just for explaination:
This error is also likely to occur in this case if (as you wrote) the ROM you are flashing does not have the resize included in it's updater script and the stock's (image's) size of the filesystem does not have enough space for ROM+GApps, as in that case the GApps' Backup and Restore script of the already installed GApps package cannot restore the GApps at the point of time when it gets called by the updater script.
