### ISSUE TITLE
OnePlus One (codename bacon / a0001) dump

### ISSUE THREAD

**Issue by ElPumpo** [Lanchon/REPIT#33]
I was bored OK?
See [repit-dump.txt](https://github.com/Lanchon/REPIT/files/244150/repit-dump.txt).

**Comment by Lanchon** [comment]
lol!! but i HAVE an OPO!!! :) i wouldn't dare tu run that stupid repit-dump thing on my phone though lol :-p

seriously, have you need the those all stupid partitions??? a 0.5GB cache! and it's far away from everything else. i like the fsc partition... 1KB? really???!!! and those reserve... and the stupid grow at the end? wtf is that!

anyway, what do you want to do with it? i hope you dont want me to move aaaaaall those partitions around, do you?

**Comment by HawaiiBeach** [comment]
Why would you not let your own One run the dump tool?

First off all, do I even need all these partitions?
Forgot to tell you that I run SultanXDA's CM13 ROM + KERNEL.

The phone being 64GB, I dont really want to mess with the paritions but it is weird, like why the hell is there free space.

So yes, I want to move everything around, as long as it doesn't give you too much to do.

Last, wont it go over the filename limit, or how do I remove partitions? There's no option to remove a partition in REPIT right?

**Comment by Lanchon** [comment]
> Why would you not let your own One run the dump tool?

lol i was kidding

hey, these are 64GB phones, i dont think it's worth moving 64GB worth of stuff around just to gain a few hundred megabytes! plus i don't know what would work or not, and i don't want to research :) this port is a no-go for me because there's too much risk and work, and very little to gain. but if someone else wants to do it...

the name would not be an issue because in REPIT you give names to interesting partitions only. no, to keep compatibility with the most roms, REPIT never deletes a partition. but you can resize them to a small size, which is what you actually care about. (note that many roms and recoveries access partitions by number, not name.)

**Comment by HawaiiBeach** [comment]
Yeah, I'd also leave it be if it takes a lot of research; thanks for the fast responce tho!
