### ISSUE TITLE
Port Request. Galaxy SHV-E120S

### ISSUE THREAD

**Issue by neps4u** [Lanchon/REPIT#34]
[repit-dump.txt](https://github.com/Lanchon/REPIT/files/250163/repit-dump.txt)

This is korean version of Galaxy S2.

Device Name : Smasung Galaxy S2 SHV-E120s
ROM : Stock 4.1.2
Kernel : Stock
Recovery : Team Win Recovery Project v 2.8.6.0
Partition layout : Running the stock partition layout

its possible to change partition layout of my device if so pleas tell how its possible.

Thanks

**Comment by Lanchon** [comment]
hi, thanks!

```
Model: MMC KTS00M (sd/mmc)
Disk /dev/block/mmcblk0: 15028MiB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
```

unfortunately your device is partitioned in the legacy "MS-DOS mode" instead of the newer GPT. i never saw a device like this before and never knew they even existed.

REPIT should in principle work on this partition type, but it has never been tested on such a setup. as such, i cannot responsibly let you test a port because something might go horribly wrong. so i won't port to this device, i'm sorry.

what you can do is:
- find a modified and properly tested PIT file for your device and reflash your phone with odin.
- or partition manually:
  - boot TWRP.
  - disable MTP.
  - unmount all partitions.
  - adb shell from your PC to it.
  - get the 'parted' binary from REPIT for any device, and adb push it to /tmp
  - chmod +x /tmp/parted
  - /tmp/parted /dev/block/mmcblk0
  - now use parted to delete the last 5 partitions (or fewer) and recreate them. don't worry about the file system inside them; instead reboot TWRP and then use TWRP to format all 5 partitions.

the partitions are:

```
24      412MiB   1310MiB   898MiB    logical   ext4
25      1312MiB  3362MiB   2050MiB   logical   ext4
26      3364MiB  3666MiB   302MiB    logical   ext4
27      3668MiB  3797MiB   129MiB    logical   ext4
28      3800MiB  15028MiB  11228MiB  logical   fat32
```

by the sizes one would guess that these partitions are:
- system
- userdata (a.k.a data)
- preload or cache
- cache or preload
- internal sdcard

before you delete them, figure out what they are: mount them all in TWRP and cat /proc/mounts

you can back them up to external sdcard before deleting them (but not the internal sdcard) and restore them later (after TWRP reboot and format).

**Comment by Lanchon** [comment]
i'm closing but you can still post here.

**Comment by neps4u** [comment]
Thank you so much for your quick response.

I have PIT File for the device, its possible to edit and create a new pit file using PIT Magic (as you are an experience on this).

I Attach the PIT Analysis txt that i created using PIT magic. 

[PIT_Analysis_002.txt](https://github.com/Lanchon/REPIT/files/250360/PIT_Analysis_002.txt)

Link for the original PIT

https://mega.nz/#!scJnzJpR!ttEJIJ_DyNoilHLdsEx_u7CUt3s-QbsYPnF_5weJAps

**Comment by Lanchon** [comment]
i don't know if PIT magic works for your device. PIT magic is a trial-and-error development that was made for GPT devices (99% of devices out there). you should really look for what other people has done and tested regarding PITs. i can't recommend that you just mod the PIT yourself: PIT magic could seriously screw up. (at least talk to PIT margic's developer about MS-DOS-partitioned devices before using it.)

if you can't find PITs for your device that were ALREADY TESTED by other people online as well as instructions on how to flash them, then i recommend that you try the 'parted' method instead. it requires you use the command line though. i can help you with issues or doubts you might have. parted is simple to use, it's an interactive program. (you will loose all data on the device.)

**Comment by neps4u** [comment]
Thanks to help.

For confirmation my mobile run normally and not found any problem untill now just one problem that is Storage.
Ok can you please guide me step by step so may be i can make this happend. 

Thanks

**Comment by Lanchon** [comment]
you need to follow the steps that start with "or partition manually" in the second message here. if you can't understand those steps i'm afraid i can't give you a more detailed how-to, because to do that i would need access to your phone.

read them and see if you can understand them. you can also read the [parted manual](https://www.gnu.org/software/parted/manual/parted.html). pay special attention to these commands:
https://www.gnu.org/software/parted/manual/parted.html#rm
https://www.gnu.org/software/parted/manual/parted.html#mkpart

note that you will be creating 'logical' partitions here in an 'msdos' style partition table.

you should NOT format the partitions you create using the command line; just format them from the TWRP menu AFTER a TWRP reboot.

**Comment by Lanchon** [comment]
you will also use the 'print' command of course:
https://www.gnu.org/software/parted/manual/parted.html#print
