### ISSUE TITLE
FATAL: this package is for 'i9100'

### ISSUE THREAD

**Issue by 4legom** [Lanchon/REPIT#5]
Hi. I don't really know the best way to contact you, i hope this is the right one. I got this error message, can you help me? The script seems to think I'm not running it on a Galaxy S2, although the device has been rightfully identified a few lines above the error. I attached the screenshot.

I have a stock ROM with TWRP 2.6.3.0 and I launched the script named: lanchon-repit-20160225-system=0.5-data=2.2-sdcard=max-preload=0.3-i9100.zip

![01](https://cloud.githubusercontent.com/assets/14137806/13375351/5dbe9c84-dd94-11e5-92fd-cae0b129a485.jpg)

**Comment by Lanchon** [comment]
unfortunately your version of TWRP does not wrap text around the end of line and you didn't pull the log otherwise, so i can't see what happened.

looks like your TWRP does not include the `getprop` command.

as per the instructions, you need to use the TWRP i published, or if not at least a recent one. you will also need an isorec compatible kernel, such as my TRIM kernel. you can go back to your current kernel after resizing.

use 'same' for the size of partitions you don't want to resize, and consider a 6 or 4 GB data partition, instead of your 2.2 choice.

thanks!

**Comment by Lanchon** [comment]
anyway, see: af3d37912521f6f5b01d1479c487587389c7ad18
