### ISSUE TITLE
Huawei Y560 (y560)

### ISSUE THREAD

**Issue by macio525** [Lanchon/REPIT#51]
Huawei Y560-L01
TWRP 3.0.2-0 unofficial [TWRP](http://www.modaco.com/forums/topic/376807-recovery-twrp-302-0-for-huawei-y5/)

Kernel: 3.10.49-g5997823-00001-gcef6b5d
release221@yep #1

CM 13: [CM 13](http://www.modaco.com/forums/topic/376952-devrom108-cyanogenmod-13-android-601-for-huawei-y5/)

Stocks partitions.

Dump: [DUMP](http://pastebin.com/raw/Xm5FdHuC)

**Comment by Lanchon** [comment]
thanks! i suppose you want to shrink system to 1GB and cache to minimum to gain 1GB extra storage, is that right?

unfortunarely there's an issue:

```
21      226MiB   258MiB   32.0MiB  ext4         persist
22      258MiB   2216MiB  1958MiB  ext4         system
23      2216MiB  2472MiB  256MiB   ext4         cache
24      2472MiB  2504MiB  32.0MiB               recovery
25      2504MiB  2505MiB  1.00MiB               devinfo
        2505MiB  2560MiB  55.1MiB  Free Space
26      2560MiB  2560MiB  0.50MiB               keystore
27      2561MiB  2624MiB  64.0MiB               oem
28      2625MiB  2625MiB  0.50MiB               config
29      2625MiB  7456MiB  4831MiB  ext4         userdata
        7456MiB  7456MiB  0.01MiB  Free Space
```

i don't know why the hell some OEMs do stuff like this! recovery after system??? jeez!

so there are 5 extraneous partitions in between system, cache and userdata:
- recovery
- devinfo
- keystore
- oem
- config

and these are the problems:
1. some devices could have silly bootloaders that somehow embed the locations of partitions instead of parsing the GPT. imagine that that is done for recovery: then, although recovery is written ok in the moved partition, the bootloader tries to read it from the old place and booting fails. now imagine that this is done for some critical partition (say, devinfo). so the bootloader cant find it and now doesn't even bring up the recovery interface (fastboot or whatever). admittedly i never verified the existence of a bootloader that doesn't parse the GPT, but i do suspect that at least some samsung devices work that way.
2. imagine that some key piece of data is stored somewhere in these partitions (say, the IMEI). what happens if REPIT dies because, i don't know, you run out of battery? your phone is a semi-brick now because you dont have backups of these partitions.

so with this in mind, do you think it is worth the risk to experiment on your phone for that extra GB?

if you want to continue, there are ways to mitigate risk. first thing, answer some questions:

a) in your phone, what happens if recovery is corrupt? how do you recover? do you have a working, unlocked fastboot mode or equivalent?
b) besides recovery, do you have any information on these 5 partitions?

thanks!

**Comment by macio525** [comment]
You know how to backup partitions with "Qualcomm HS-USB Android DIAG 901D" ?

**Comment by Lanchon** [comment]
no idea about anything proprietary. but you didn't answer my questions!

**Comment by macio525** [comment]
a. I have unlocked fastboot
b. What u mean.?

**Comment by Lanchon** [comment]
so please confirm that you can flash recovery via fastboot.

then, this is what i propose:

1) backup the partitions.
2) make a reduced repit for you that only works on system and recovery.
3) reduce system a bit and move recovery a bit closer to the start of the disk.
4) test booting into recovery. if it works, it is because the bootloader reads the GPT.
5) flash recovery with fastboot.
6) test booting into recovery. if it works, it is because the fastboot reads the GPT.
7) assume that the bootloader reads the GPT for all partitions (safe assumption if you ask me) and do a full repit version.

it is vital that you have working android with root in android, just in case. the recovery might not work.

otherwise i can build a full repit and you can risk it.

or otherwise we could do nothing.

what do you think?

**Comment by macio525** [comment]
3) how to do this?

**Comment by Lanchon** [comment]
with a reduced version of repit for your device that i would create if you want to go ahead with this.

**Comment by macio525** [comment]
i will try

**Comment by Lanchon** [comment]
ok. start by backing up your 5 partitions:
recovery
devinfo
keystore
oem
config

from the pc you can do:
`adb root`
then for each partition:
`adb pull /dev/block/platform/7824900.sdhci/by-name/{{the-partition-name-here}}`

**Comment by macio525** [comment]
you mean?
adb pull /dev/block/platform**/soc.0**/7824900.sdhci/by-name/

**Comment by Lanchon** [comment]
actually forget about adb root, and instead boot into TWRP, connect via adb to TWRP, now run the adb pull commands there (the exact way i typed them)

**Comment by macio525** [comment]
done
![1](https://cloud.githubusercontent.com/assets/20195493/19186690/c355188c-8c87-11e6-89de-653adcc8038a.PNG)

**Comment by Lanchon** [comment]
ok i'll prepare repit for your device when i have some time!

**Comment by macio525** [comment]
**I NEVER installed CM 12.1**... how the hell he got there?
ro.cm.display.version]: [12.1-20160420-UNOFFICIAL-KonstaKANG-y560
ro.cm.version]: [12.1-20160420-UNOFFICIAL-KonstaKANG-y560
ro.modversion]: [12.1-20160420-UNOFFICIAL-KonstaKANG-y560

**Comment by Lanchon** [comment]
what are you talking about?

**Comment by macio525** [comment]
i mean CM 12.1 lines in [dump file](http://pastebin.com/raw/Xm5FdHuC)
when i never installed CM 12.1

**Comment by the-gangster** [comment]
Nothing to worry about.
These are values that are read out of the ramdrive that was used to create the recovery.
I'd bet if you'd extract your devices recovery, you would find these values in its ramdrives /default.prop file.
It's the same for i9100 device.

**Comment by macio525** [comment]
You make it?

**Comment by Lanchon** [comment]
no, sorry. i'll do it now.

**Comment by Lanchon** [comment]
hi, sorry for the delay!

here is the test build. the test procedure is:
1. back up valuable information from your phone to your PC or some external storage.
2. boot android and **verify that you have working root** to help us recover in case of trouble.
3. download this test build: [lanchon-repit-y560_test.tar.gz](https://github.com/Lanchon/REPIT/files/527826/lanchon-repit-y560_test.tar.gz).
4. extract the test zip inside and copy it to your sdcard. **do not alter the name of the test zip in any way.**
5. boot twrp and flash the test REPIT according to instructions on REPIT's main page.
6. **obtain a copy of the repit log and paste it here**.
7. reboot recovery.

this test zip will shrink cache from 256MB to 255MB and move the recovery partition closer to the start of the drive by 1MB.

if recovery boots from its new location, then this would be a clear indication that the bootloader of your device is reading partition information from the standard GPT partition table. this in turn would mean that we can probably move the problematic partitions (24 through 28) as required without causing issues.

**Comment by macio525** [comment]
recovery dont work after flash
and cant turn on device
when i connect to pc i got Qualcomm HS-USB Diagnostics 900E

**Comment by Lanchon** [comment]
wow this is unexpected. can you post the log?

**Comment by macio525** [comment]
its said "success" but how i can show u the log?

**Comment by Lanchon** [comment]
well now you can't if you turned off the phone. that's way i asked you to pull the log before rebooting.

so i looked on the web and found this thread... by you! so have you previously bricked your device? you already know how to fix it?
http://forum.xda-developers.com/android/help/huawei-y560-l01-bricked-t3451958

**Comment by macio525** [comment]
bootloader lock by yourself

**Comment by Lanchon** [comment]
please try to write more crearly, i can't really understand those short messages.
1. please confirm that your bootloader was unlocked before trying repit
2. is your bootloader unlocked now?
3. do you already know how to recover from this using qualcomm tools?

**Comment by Lanchon** [comment]
4.can you boot in fastboot mode?

**Comment by macio525** [comment]
i cant boot in fastboot mode
and yes, i have unlocked bootloader before repit

**Comment by Lanchon** [comment]
ok you are in qualcomm's EDL. do you know how to recover from this using qualcomm tools?

**Comment by macio525** [comment]
i try do something but...

**Comment by macio525** [comment]
but idk how to make test point i have 3 pins: VCOM, DM and UP near USB

**Comment by Lanchon** [comment]
why do you need test points? the device is already in download mode, isnt it?

**Comment by Lanchon** [comment]
"Qualcomm HS-USB Diagnostics 900E"

**Comment by macio525** [comment]
it should be QDLoader

**Comment by macio525** [comment]
someone bricked and got QDLoader "Hi. I need help!!! My Huawei y560-L01 bricked after flashing rom, nothing is working, just flash screen with huawei logo and dark. In menager is as **Qualcomm HS-USB QDLoader 9008.** No phone visible. Any idea?"

**Comment by Lanchon** [comment]
but YOU posted that a couple of months ago!
http://forum.xda-developers.com/android/help/huawei-y560-l01-bricked-t3451958

**Comment by macio525** [comment]
yes and after 6 hours i enter to fastboot mode and try to unlock fastboot(was unlocked before..)

**Comment by Lanchon** [comment]
maybe you want to read this:
http://www.androidbrick.com/ultimate-qualcomm-snapdragon-unbrick-guide-snapdragons-are-unbrickable-qhsusb_dload_qpst_qfil/

**Comment by Lanchon** [comment]
http://www.droidsavvy.com/unbrick-qualcomm-mobiles/

**Comment by macio525** [comment]
"First question as always, what did you do to 'brick' your device?

There's no firmware available that you could flash with QPST and those files don't necessarily get you very far. Maybe you can dump the whole eMMC from another working device and restore it on the broken one."

KonstaT from modaco.com

**Comment by Lanchon** [comment]
i don't know what bricked the device. the standard gdisk was used to change 2 partitions, cache and recovery. nothing else was changed. it looks like maybe the bootloader does some kind of signature verification on the GPT, which in effect means that the device was not really fully unlocked.

**Comment by Lanchon** [comment]
if you could enter fastboot, the phone would probably recover simply by flashing the GPT. (it would still not enter recovery unless a recovery is flashed. and the cache/ would be 1MB smaller than usual until you format it.)

it seems that you need to flash the stock GPT and that will suffice. i don't know what tools could be used for that.

**Comment by macio525** [comment]
stock gpt? that one?
![image](https://cloud.githubusercontent.com/assets/20195493/19367036/cb19eb26-9199-11e6-97b7-7168e57f966b.png)

**Comment by Lanchon** [comment]
the GPT file for qualcomm fastboot is generally called gpt.bin and can be found in stock images. it is usually flashed using "fastboot flash partition gpt-XXX.bin".

http://forum.xda-developers.com/showpost.php?p=68819815&postcount=30

you cannot pull it as you pull a partition because it is not a partition, it is the partition table. i don't know if the format of the gpt.bin file is known.

**Comment by macio525** [comment]
Ok, im done ;/

**Comment by Lanchon** [comment]
so were you able to recover???? holy $#!+ !!! i'm so glad!

**Comment by Lanchon** [comment]
thank you for trying. this is the first time a device is bricked by REPIT.

i don't know why it happened, it looks like some kind of anti-tamper protection for the GPT in the bootloader. i don't think huawei is clever enough to do this by themselves, so i have to conclude that qualcomm is probably behind this.

**and the corollary is that this issue might affect other recent qualcomm devices.**

i have decided not to process port requests for newer qualcomm devices because of this, unless there is a clear unbricking path and the requester is aware of all the facts. in any case, most newer devices are partitioned in a mostly-sane way; the motivation for creating REPIT was fixing older devices with problematic partition layouts.

i'm very glad that you were able to recover your device; you were lucky. i hope this never happens again.

thanks again!

**Comment by macio525** [comment]
i mean I'm done with trying to recover this phone :'/
i need file "prog_emmc_firehose_8909.mbn"
and convert those files:
[partition.xml](http://pastebin.com/raw/xKpFmuk0)
[patch0.xml](http://pastebin.com/raw/qNvWqcJY)
and [rawprogram0.xml](http://pastebin.com/raw/VYyH8qYS)

**Comment by Lanchon** [comment]
oh crap i'm sorry to hear that!!

apparently you can download the firmware from:
https://boycracked.com/tag/unbrick-huawei-ascend-y5-y560-l01/

the follow instrctions here:
**WARNING: THESE FILES MIGHT BE TROJANS**
https://boycracked.com/2016/01/22/how-to-installing-the-firmware-using-qfil-for-all-android-device-based-on-qualcomm-chips/

but that might require "QDLoader 9008" and you have "Diagnostics 900E". have you tried this?

**Comment by macio525** [comment]
i need to find that file prog_emmc_firehose_8909.mbn
and i have those files
![image](https://cloud.githubusercontent.com/assets/20195493/19400401/543e6910-9256-11e6-9853-62144ab69b38.png)

**Comment by Lanchon** [comment]
**WARNING**

Hello, fellow QPST users.

QPST 2.7 Build 4.2.2 is a fake version with keylogger.
Some a$$hole downloaded latest public QPST build (4.0.2) and decompiled MSI installer package, then edited all "4.0.2" to "4.2.2", added "fake changelog", added keylogger (qualcomm.exe), then repackaged and spread around web!

http://forum.xda-developers.com/showpost.php?p=49729779&postcount=7

**Comment by Lanchon** [comment]
which country are you in? in which country was the phone bought?

**Comment by macio525** [comment]
Poland

**Comment by Lanchon** [comment]
im downloading one of the firmwares to see what is inside. i will be another 30 minutes

**Comment by Lanchon** [comment]
are you able to enter QDLOAD? it seems to be necessary for QPST.

with the phone completely off:
Connect your phone to PC through a USB cable pressing VOL-
--- If VOL- doesn't work try several combinations, like VOL+/USB cable or VOL-/VOL+/USB ---

**Comment by Lanchon** [comment]
apparently if the battery gets fully discharged in this state, then it is even more complicated to continue.

**Comment by Lanchon** [comment]
your phone has a MSM8916 chip, i think.

why do you think you need this file?
prog_emmc_firehose_8909.mbn

**Comment by Lanchon** [comment]
the zip only has these firmware files:
-rw-r--r-- 1 rod rod   441900 Aug 23  2013 emmc_appsboot.mbn
-rw-r--r-- 1 rod rod  1048576 Aug 23  2013 misc.bin
-rw-r--r-- 1 rod rod 49759744 Aug 23  2013 NON-HLOS.bin
-rw-r--r-- 1 rod rod   159596 Aug 23  2013 rpm.mbn
-rw-r--r-- 1 rod rod   246996 Aug 23  2013 sbl1.mbn
-rw-r--r-- 1 rod rod   523304 Aug 23  2013 tz.mbn

nothing related to the GPT i think. it seems you will have to copy the GPT (the start and end of the eMMC) from another identical phone (i don't know if you will be able to read an write using qualcomm tools, no idea) or else take it to a repair shop to have it reflashed. i'm very sorry.

**Comment by macio525** [comment]
Qualcomm Snapdragon 210 MSM8909

**Comment by macio525** [comment]
but i still see boot logo(splash partition)

**Comment by macio525** [comment]
test point ideas?
![20161017_133935](https://cloud.githubusercontent.com/assets/20195493/19436879/fc473dc6-9472-11e6-9c8e-e0cb04981ca8.jpg)

**Comment by Lanchon** [comment]
no idea. i dont know why you want a test point for. i'm not familiar with qualcomm chips. do you want to put the device in bulk mode?

the ones near the batt connector seem to be the micro USB port.

SDA/SCL etc are probably an i2c bus of some sort, to whatever was connected there. (touch sensor?)

then there is that nice BOOT pin....

are you supposed to ground it? i'm afraid you might break your hardware if you continue.
whatever you do, use a resistor to connect the pins to ground (or whatever). something above 10K should probably be safe.

if you are able to switch to bulk mode, DONT WRITE ANYTHING! you need data taken from a working devices that is exactly the same model.

**Comment by nishimura-san** [comment]
![fc473dc6-9472-11e6-9c8e-e0cb04981ca8](https://cloud.githubusercontent.com/assets/3609965/19498730/515dff38-959b-11e6-8017-c94db50cb06d.jpg)

**Comment by Lanchon** [comment]
boot could be a boot selection pin. the easiest test you can do is ground it and with the pin grounded and the device off, connect the device to the PC and see if there are any changes in how it recognizes it.

otherwise you can connect it to a power source pad, but you can destroy the soc if u connect it to the wrong voltage.

ALWAYS USE A RESISTOR IN SERIES to protect the soc. connect the soc pin to power or ground through the resistor: one side of the resistor to boot, the other to ground or Vdd. a good value for the resistor is 10K ohm.

take ESD precautions: touch the phone's ground before touching any other trace. avoid carpets and dry air (turn off the A/C).

**Comment by Lanchon** [comment]
you can also try the other pin if you want afterwards.

the SDA/SCL dont look like JTAG, they could be breakout pins of the nearby connector just like in the case of the USB. or maybe they are dual mode, who knows, its anybodys guess.

**Comment by macio525** [comment]
i try connect it to ground with battery and still recognize it as HS_USB 900E
without battey nothing happens

**Comment by macio525** [comment]
When i connect ground + DM it disconnects other devices for a 0.5 sec from PC. Without connected other devices to PC nothing happens.

**Comment by Lanchon** [comment]
don't continue. i think you just shortcircuited a usb line. i suppoese you can only do that if you are NOT using a resistor as i said before that you ahould. you can very really destroy the hardware that way. you need to take the device to service for a reflash.

**Comment by Lanchon** [comment]
suspicious strings found in bootloader:

```
$ strings emmc_appsboot.mbn | grep -i gpt | grep -i sign

GPT: Primary and backup signatures invalid
GPT: Primary signature invalid cannot write GPT
GPT: Backup signature invalid cannot write GPT
```

device assumed to use GPT signature checking.
