### ISSUE TITLE
i9100 either not resizing or not recognising system partition after using REPIT

### ISSUE THREAD

**Issue by new-to-this** [Lanchon/REPIT#77]
Dear Lanchon,

I'm new to GitHub, and I'm not a programmer, so I apologise if my approach or etiquette is wrong.

I've unsuccessfully attempted to use REPIT, and my device is now either not resizing the /system partition (which is unchanging at 495MB) or not recognising the system partition at all. 

I've lost my OS (Lineage) as part of my blundering, which will not now reinstall, presumably due to the size of the system partition

The dump file indicates errors, but I'm not knowledgeable enough to interpret and act on what I'm reading.

Device: Samsung Galaxy S2 i9100 international version
Recovery; TWRP 3.1.0-0 (bundled with kernel)
Kernel: Dorimanx-V11.0b026 [08:58 | 04.02.2016
Rom:  was Lineage-14.1-20170531-nightly-i9100

[repit-dump.log[1].txt](https://github.com/Lanchon/REPIT/files/1060886/repit-dump.log.1.txt)

If this is an appropriate means of raising this with you, could you help please?

Regards,

Mark

**Comment by Lanchon** [comment]
hi Mark,

no, it is not.

- you *HAVE* to provide the log of the repit operation, otherwise no one can help you. read repit docs to find out how to get logs. repit again and capture log this time.

- please post your issue here:
https://forum.xda-developers.com/android/software-hacking/tool-lanchon-repit-data-sparing-t3358036
other people will be able to help you there. repit has very good user-provided support by some very cool users. me, i'm way too busy at the moment, sorry.

- the repit-dump thing you ran has absolutely nothing to do with your issue. (read docs to find out why... if you want.)

thanks!
