### ISSUE TITLE
Samsung Galaxy S3 US Cellular SCH-R530U (d2usc)

### ISSUE THREAD

**Issue by TeracottaShishi** [Lanchon/REPIT#97]
**Device:** SCH-R530U
**Codename:** d2usc
**Recovery:** TWRP 3.3.1.0
**Kernel:**
3.0.31-1131058
se.infra@SEP-133 #2 
SMP PREEMPT Thu Apr 18 23:22:09 KST 2013
**ROM:** TouchWiz 4.1.2
**is your device running the stock partition layout or is it already modified?:** no modification

[repit-dump.log](https://github.com/Lanchon/REPIT/files/3615758/repit-dump.log)

**Comment by Lanchon** [comment]
here is a test build for your device

1) download and EXTRACT this zip file:
[EXTRACT-THIS-ZIP-(d2-test).zip](https://github.com/Lanchon/REPIT/files/3818136/EXTRACT-THIS-ZIP-.d2-test.zip)
2) READ REPIT INSTRUCTIONS.
3) if you flash as-is, you will gain 0.8 GB in /data taken from /cache. this should be quick and safe.
4) if you RESIZE /SYSTEM and NOT WIPE /DATA **AT THE SAME TIME USING REPIT**, the operation will take a VERY LONG WHILE. this is because the huge data partition must be moved around in the disk.
5) resizing /system requires moving /data. if this operation is interrupted, you WILL loose your data. READ THE REPIT INSTRUCTIONS CAREFULLY BEFORE USING.

thanks!

**Comment by Lanchon** [comment]
please note that there is a risk involved in trying this. some devices have signed partition tables and will refuse to boot with a modified partition table. in this case, the device would be hard-bricked. typically this protection showed up on later devices (you device is old), and this is the reason ive mostly stopped work on REPIT. i would expect you are not affected, but there is no way to know.

**Comment by Lanchon** [comment]
you can use the `strings` command on an image of the bootloader partition to try get hints regarding GPT signatures. read about it in the GPT signing issues that are open here.

**Comment by TeracottaShishi** [comment]
thank you!!

I will try this out this weekend, I have a second device for testing this.

**Comment by Lanchon** [comment]
please remember to tell me if it worked or otherwise post a log, thanks!

**Comment by Lanchon** [comment]
i don't know if i should commit this or roll it back. you didn't try it?

**Comment by TeracottaShishi** [comment]
hi, I have been very busy, and had not opportunity to use the device
I apologize, when the holiday gets closer I'll be able to give it chance

JP

**Comment by TeracottaShishi** [comment]
hello lanchon, I apologize, this thread got archive and I forget about it.

I tested repit in January and have been using it for the past 5
months. it works perfectly with this device, the tables are not signed
like with the S4+

thank you much for working on this

JP

**Comment by Lanchon** [comment]
thanks for getting back. i've just pushed and released the version. ;)
